### ISSUE TITLE
HTML in Beschreibung

### ISSUE THREAD

**Issue by saerdnaer** [MunichWays/daten#1]
Aktuell werden Bilder oder anderes HTML Markup in der Beschreibung in uMap nicht richtig dargestellt:

![image](https://user-images.githubusercontent.com/40266/51090159-e7433800-1777-11e9-902a-a2b3e2398694.png)

Zu klären: Sollte man das HTML im Skript anders oder gar nicht escapen, oder ist das eher ein Fehler von uMap?

**Comment by thomas-munichways** [comment]
siehe https://github.com/AppWerft/MunichWays
und https://www.munichways.com/radlvorrangnetz/
