### ISSUE TITLE
Styles/Farben mit exportieren?

### ISSUE THREAD

**Issue by saerdnaer** [MunichWays/daten#2]
Aktuell werden die Styles aus dem Master-File nicht mit in die Folder-Files kopiert. Allerdings könne uMap wohl so oder so nicht damit anfagen... Optimieren?

Ggf. sollten man die Styles vorher mal auf ein paar sinnvolle Wenige (z.B. grün, gelb, rot, schwarz) zusammenschrumpfen

**Comment by thomas-munichways** [comment]
siehe https://github.com/AppWerft/MunichWays
und https://www.munichways.com/radlvorrangnetz/
